### ISSUE TITLE
Prettier does not appear to respect "ignore trim whitespace" setting in VSCode

### ISSUE THREAD

**Issue by ajyong** [devedmonton/codevid19.com#86]
I'll add repro steps soon™, but essentially the format-on-save is getting rid of trailing whitespace in Markdown files even though I thought I had set VSCode's settings to allow trailing whitespace.

That, or we just disallow the "two spaces at end = line break" behavior of Markdown.  Personally, I didn't even know that was a thing until I saw one of the blog posts use it.

**Comment by ajyong** [comment]
At the moment, the workaround is to use `<br>` in place of two spaces at the end

**Comment by MandyMeindersma** [comment]
marked as out of scope
